name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.2.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.4.1
  easy_date_timeline:  ^1.0.6
  shared_preferences: ^2.5.3
  lottie: ^3.3.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/
    - assets/images/
