name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization & Date
  intl: ^0.19.0
  easy_date_timeline: ^1.0.6

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.2.0

  # State Management
  provider: ^6.1.5

  # UI & Utils
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.5.3
  lottie: ^3.3.1

  # Local DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Image Picker (Android + iOS + Web)
  file_picker: ^10.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
